FROM scratch
LABEL Maintainer="Cezar"
LABEL Description="Add alpine from .tar on the very base image from docker called scratch. I suppose you cannotgo more basic than this!"
ADD files/alpine-minirootfs-3.8.2-x86_64.tar.gz /
CMD ["/bin/sh"]

